-- Seed initial categories (idempotent)
INSERT INTO "categories" ("id", "name", "createdAt") VALUES
  (gen_random_uuid()::text, 'Banner', NOW()),
  (gen_random_uuid()::text, 'Móbile', NOW()),
  (gen_random_uuid()::text, 'Wobbler', NOW()),
  (gen_random_uuid()::text, 'Stopper', NOW()),
  (gen_random_uuid()::text, 'Faixa de gôndola', NOW()),
  (gen_random_uuid()::text, 'Totem', NOW()),
  (gen_random_uuid()::text, 'Ilha', NOW()),
  (gen_random_uuid()::text, 'Ponta de gôndola', NOW()),
  (gen_random_uuid()::text, 'Balcão de degustação', NOW()),
  (gen_random_uuid()::text, 'Clip strip', NOW()),
  (gen_random_uuid()::text, 'Fita cross', NOW()),
  (gen_random_uuid()::text, 'Take one', NOW()),
  (gen_random_uuid()::text, 'Cartaz', NOW()),
  (gen_random_uuid()::text, 'Precificador', NOW()),
  (gen_random_uuid()::text, 'Saia de palete', NOW()),
  (gen_random_uuid()::text, 'Adesivo de piso', NOW()),
  (gen_random_uuid()::text, 'Pórtico', NOW()),
  (gen_random_uuid()::text, 'Backdrop', NOW()),
  (gen_random_uuid()::text, 'Wind banner', NOW()),
  (gen_random_uuid()::text, 'Cubo promocional', NOW()),
  (gen_random_uuid()::text, 'Mockup', NOW()),
  (gen_random_uuid()::text, 'Glorificador', NOW()),
  (gen_random_uuid()::text, 'Stopper luminoso', NOW()),
  (gen_random_uuid()::text, 'Corner', NOW()),
  (gen_random_uuid()::text, 'Flange', NOW()),
  (gen_random_uuid()::text, 'Stopper de carrinho', NOW()),
  (gen_random_uuid()::text, 'Testeira', NOW()),
  (gen_random_uuid()::text, 'Cantoneira', NOW()),
  (gen_random_uuid()::text, 'Stopper de prateleira', NOW()),
  (gen_random_uuid()::text, 'Cartazete', NOW()),
  (gen_random_uuid()::text, 'Separador de compras', NOW()),
  (gen_random_uuid()::text, 'Porta-folheto', NOW()),
  (gen_random_uuid()::text, 'Totem fotográfico', NOW()),
  (gen_random_uuid()::text, 'Totem interativo', NOW()),
  (gen_random_uuid()::text, 'Balcão promocional', NOW()),
  (gen_random_uuid()::text, 'Saia de gôndola', NOW()),
  (gen_random_uuid()::text, 'Banner suspenso', NOW()),
  (gen_random_uuid()::text, 'Cubo de papelão', NOW()),
  (gen_random_uuid()::text, 'Tapete personalizado', NOW()),
  (gen_random_uuid()::text, 'Cavalete', NOW()),
  (gen_random_uuid()::text, 'Brinde', NOW()),
  (gen_random_uuid()::text, 'Display', NOW()),
  (gen_random_uuid()::text, 'Amostra', NOW()),
  (gen_random_uuid()::text, 'Forração', NOW())
ON CONFLICT ("name") DO NOTHING;
